name: 12_SecureCodingPipelineWithNetCore

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    displayName: 'Secure Coding - Install .NET Core SDK (auto-injected)'
    inputs:
      version: 8.x
      performMultiLevelLookup: true
      includePreviewVersions: true