name: 07_DebugPipelineDecorator

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  system.debugContext: 'true'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'